config/routes.rb
CTGService::Application.routes.draw do

  get "access_denied/index"

  get 'admin' => 'admin#index'

 controller :sessions do
    get 'login' => :new
    post 'login' => :login
    delete 'logout' => :logout
    get 'sign up' => :new
  end

  resources :users

  resources :event_types

  resources :upcomingevents

  root :to => "admin#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/upcomingevent.rb
class Upcomingevent < ActiveRecord::Base

  validates :name, :presence =>true
  validates :location, :presence =>true
  validates :description, :presence =>true

  validates :timestart, d :presence => true
  validates :timeexpire, :presence => true



end

app/controllers/upcomingevents_controller.rb
class UpcomingeventsController < ApplicationController

    load_and_authorize_resource

    #before_filter :authenticate, :except => [:login]
    # GET /upcomingevents
    # GET /upcomingevents.xml

    def index

      @upcomingevents = Upcomingevent.find(:all, :order => 'timestart')

      respond_to do |format|
        format.html # index.html.erb
        format.xml { render :xml => @upcomingevents }
      end


    end

    # GET /upcomingevents/1
    # GET /upcomingevents/1.xml
    def show

      @upcomingevent = Upcomingevent.find(params[:id])





      respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @upcomingevent }
      end
    end


    # GET /upcomingevents/new
    # GET /upcomingevents/new.xml

    def new

      @upcomingevent = Upcomingevent.new



      respond_to do |format|
        format.html # new.html.erb
        format.xml { render :xml => @upcomingevent }
      end


    end

    # GET /upcomingevents/1/edit
    def edit

      @upcomingevent = Upcomingevent.find(params[:id])
    end

    # POST /upcomingevents
    # POST /upcomingevents.xml
    def create

      @upcomingevent = Upcomingevent.new(params[:upcomingevent])

      respond_to do |format|
        if @upcomingevent.save
          format.html { redirect_to(@upcomingevent, :notice => 'Upcomingevent was successfully created.') }
          format.xml { render :xml => @upcomingevent, :status => :created, :location => @upcomingevent }
        else
          format.html { render :action => "new" }
          format.xml { render :xml => @upcomingevent.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /upcomingevents/1
    # PUT /upcomingevents/1.xml
    def update

      @upcomingevent = Upcomingevent.find(params[:id])

      respond_to do |format|
        if @upcomingevent.update_attributes(params[:upcomingevent])
          format.html { redirect_to(@upcomingevent, :notice => 'Upcomingevent was successfully updated.') }
          format.xml { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml { render :xml => @upcomingevent.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /upcomingevents/1
    # DELETE /upcomingevents/1.xml
    def destroy


      @upcomingevent = Upcomingevent.find(params[:id])
      @upcomingevent.destroy

      respond_to do |format|
        format.html { redirect_to(upcomingevents_url) }
        format.xml { head :ok }
      end
    end


    protected
    def authenticate

    end

  end

app/helpers/upcomingevents_helper.rb
module UpcomingeventsHelper
end

app/views/upcomingevents/_form.html.erb
<%= form_for(@upcomingevent) do |f| %>




    <% if @upcomingevent.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@upcomingevent.errors.count, "error") %> prohibited this upcomingevent from being
            saved:</h2>

          <ul>
            <% @upcomingevent.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>




        <div>
          <%= f.label :name %>
          <br/>

          <%= f.text_field  :name, :size =>55 %>
        </div>

        <div>
          <%= f.label :description %>
          <br/>

          <%= f.text_area :description ,:size =>55%>
        </div>

        <div>
          <%= f.label :location %>
          <br/>

          <%= f.text_field :location ,:size =>55 %>
        </div>

        <div>
          <%= f.label :ref, "reference" %>  <br/>
          <%= f.text_field :ref ,:size =>55 %>
        </div>


        <div>
          <%= f.label :timestart %>
          <br/>
          <%= f.datetime_select :timestart %>
        </div>

        <div>
          <%= f.label :timeexpire %>
          <br/>
          <%= f.datetime_select :timeexpire, :default => 1.minutes.from_now %>
        </div>

        <div>
          <%= f.submit %>
        </div>

    <% end %>

app/views/upcomingevents/edit.html.erb
<div class="bluebox" align="center">
  <h2>Editing upcomingevent</h2>
</div>
</br>
<div class="bluebox" style="text-align: left">
  <%= render 'form' %>

  <%= link_to '', @upcomingevent %> | <%= link_to 'Back', upcomingevents_path %>
</div>

app/views/upcomingevents/index.html.erb
<div class="bluebox" align="center">
  <h2>Event list</h2>
</div>
</br>

<div class="bluebox" align="center">
  <table rules="rows" frame="below">
    <tbody>
    <tr>
      <th colspan="6" style="text-align: right;">
        <form method="new_upcomingevent_path" action="/upcomingevents/new" class="button_to">
          <div>
            <input type="submit" value="Add event">

          </div>
        </form>
      </th>
    </tr>
    <th style="width: 255px" align="left">Name</th>
    <th style="width: 50px;text-align: left;"></th>
    <th style="width: 40px;text-align: left;"></th>
    <th style="width: 60px;text-align: left;"></th>



    <th align="right">
      <a href="/upcomingevents.xml">XML file</a>
    </th>
    <!-- <th>Description</th>
  <th>Location</th>
  <th>Time start</th>
  <th>Time expire</th>
  <th></th>
  <th></th>
  <th></th>  -->
    </tr>

    <% @upcomingevents.each do |upcomingevent| %>
        <tr>
          <td><%= upcomingevent.name %></td>
          <!--<td><%= upcomingevent.description %></td>
    <td><%= upcomingevent.location %></td>
    <td><%= upcomingevent.timestart %></td>
    <td><%= upcomingevent.timeexpire %></td>  -->
          <td><%= link_to 'Detail', upcomingevent %></td>
          <td><%= link_to 'Edit', edit_upcomingevent_path(upcomingevent) %></td>
          <td><%= link_to 'Delete', upcomingevent, :confirm => 'Are you sure?', :method => :delete %></td>
          <td><a href="<%= upcomingevent_path(upcomingevent) %>.xml">xml</a></td>


        </tr>
        </tbody>
    <% end %>
    </table>
  <table align="left">
  <tr>
  <th style="" align="left">
  <%= link_to 'Back', :controller => 'admin',:action => 'index'%>
  </th>
  </tr>
      </table>
</div>

app/views/upcomingevents/new.html.erb
<div class="bluebox" align="center">
  <h2>Add Event</h2>
</div>
</br>
<div class="bluebox" style="text-align: left">

  <%= render 'form' %> |<%= link_to 'Back', upcomingevents_path %>
</div>

app/views/upcomingevents/show.html.erb
<p align="center" id="notice"><%= notice %></p>

<div class="bluebox" style="text-align: center">
  <h2><%= @upcomingevent.name %></h2>
</div>
</br>
<div class="bluebox" align="left">
  <table>
    <tbody>


    <p>
      <b>Description:</b>
      <%= @upcomingevent.description %>
    </p>

    <p>
      <b>Location:</b>
      <%= @upcomingevent.location %>
    </p>

    <p>
      <b>Reference:</b>
      <%= @upcomingevent.ref %>
    </p>

    <p>
      <b>Timestart:</b>
      <%= @upcomingevent.timestart %>
    </p>

    <p>
      <b>Timeexpire:</b>
      <%= @upcomingevent.timeexpire %>
    </p>


    <%= link_to 'Edit', edit_upcomingevent_path(@upcomingevent) %> |
    <%= link_to 'Back', upcomingevents_path %>
    </tbody>
  </table>
</div>