config/routes.rb
CTGService::Application.routes.draw do

  get "access_denied/index"

  get 'admin' => 'admin#index'

 controller :sessions do
    get 'login' => :new
    post 'login' => :login
    delete 'logout' => :logout
    get 'sign up' => :new
  end

  resources :users

  resources :event_types

  resources :upcomingevents

  root :to => "admin#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
require 'digest/sha1'


class User < ActiveRecord::Base
  
  validates_presence_of     :name
  validates_uniqueness_of   :name
 
  attr_accessor :password_confirmation
  validates_confirmation_of :password

  validate :password_non_blank
  

  
  def self.authenticate(name, password)
    user = self.find_by_name(name)
    if user
      expected_password = encrypted_password(password, user.salt)
      if user.hashed_password != expected_password
        user = nil
      end
    end
    user
  end
  
  
  # 'password' is a virtual attribute
  
  def password
    @password
  end
  
  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.hashed_password = User.encrypted_password(self.password, self.salt)
  end
  
  

private

  def password_non_blank
    errors.add(:password, "Missing password") if hashed_password.blank?
  end

  
  
  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  
  
  def self.encrypted_password(password, salt)
    string_to_hash = password + "wibble" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_filter :authenticate, :except => [:login]
  # GET /users
  # GET /users.xml
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @user }
    end

  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        #format.html {redirect_to  :controller => 'admin' , :action =>  'login' }

        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        #format.html { redirect_to(user_url,
         #                         :notice => "User was successfully created.") }
        format.xml { render :xml => @user,
                            :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user.errors,
                            :status => :unprocessable_entity }
         #redirect_to(:controller => "admin",:action => "login")
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        #format.html { redirect_to(users_url,
         #                         :notice => "User #{@user.name} was successfully updated.") }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @user.errors,:status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    begin
      flash[:notice] = "User #{@user.name} delete"
      @user.destroy
    rescue Exeption => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml { head :ok }
    end

  end

  #protected
  #def authenticate

  #end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %>
            prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>



    <table>
      <tr>
      <td>
        <%= f.label :name %>
      </td>
      <td>
        <%= f.text_field :name %>
      </td>
      </tr>
      <tr>
      <td>
        <%= f.label 'Password' %>
      </td>
      <td>
        <%= f.password_field :password %>
      </td>
       </tr>
        <tr>
      <td>

        <%= f.label 'Confirm' %>
        </td>
      <td>
        <%= f.password_field :password_confirmation %>
      </td>
      </tr>
      <tr>
         <td>
        <%= f.submit %>
        </td>
      </tr>
        </table>

<% end %>

app/views/users/edit.html.erb
<div class="bluebox" align="center">
  <h2>Editing user</h2>
</div>
</br>
<div class="bluebox" style="text-align: left">
  <%= render 'form' %>

  <%= link_to '', @user %> | <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="bluebox" align="center">
  <h2>Listing users</h2>
</div>
</br>

<div class="bluebox" align="center">
  <table rules="rows" frame="below">
    <tbody>
    <tr>
      <th colspan="6" style="text-align: right;">
        <form method="New User" action="/users/new" class="button_to">
          <div>
            <input type="submit" value="New users">
          </div>
        </form>
      </th>
    </tr>
    <tr>
      <th style="width: 100px" align="left">User</th>
      <th style="width: 50px;text-align: left;"></th>
      <th style="width: 40px;text-align: left;"></th>

    </tr>

    <% for user in User.all do %>


        <td><%= user.name %></td>

        <td><%= link_to 'Detail', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, :confirm => 'Are you sure?',
                        :method => :delete %></td>
        </tr>
    <% end %>

    <!--%= link_to 'Back', :controller => "admin", :action =>"login" %-->


    </tbody>
  </table>
  <table align="left">
    <tr>
      <th style="" align="left">
        <%= link_to 'Back', :controller => 'admin', :action => 'index' %>
      </th>
    </tr>
  </table>
</div>

app/views/users/new.html.erb
<div class="bluebox" align="center">
<h2>New user</h2>
</div>
</br>

<div class="bluebox" style="text-align: left">
<%= render 'form' %>  |
  <%= link_to 'Back', users_path %>

<!--%= link_to 'Back', :controller => 'admin',:action => 'login'%-->
    </div>

app/views/users/show.html.erb
<p align="center" id="notice"><%= notice %></p>
<div class="bluebox" style="text-align: center">
  <h2><%= @user.name %></h2>
  </div>
</br>
<div class="bluebox" align="left">
  <table>
    <tbody>

  <p>
    <b>Hashed password:</b>
    <%= @user.hashed_password %>
  </p>

  <p>
    <b>Salt:</b>
    <%= @user.salt %>
  </p>



  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
      </tbody>
      </table>
</div>