config/routes.rb
CTGService::Application.routes.draw do

  get "access_denied/index"

  get 'admin' => 'admin#index'

 controller :sessions do
    get 'login' => :new
    post 'login' => :login
    delete 'logout' => :logout
    get 'sign up' => :new
  end

  resources :users

  resources :event_types

  resources :upcomingevents

  root :to => "admin#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :event_type

  validates :name, :presence =>true
  validates :location, :presence =>true
  validates :description, :presence =>true
  validates :time_start, :presence =>true
  validates :time_expire, :presence =>true

end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  has_many :events
  validates :type, :presence =>true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate, :except => [:login]
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events.to_xml}
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event.to_xml }

    end
  end

  # GET /events
 # def xml
  #  @events = Event.all

   # respond_to do |format|
    #  format.xml { render :xml =>@}
    #end
  #end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event.to_xml }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event.to_xml, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name ,
        :rows => 3,
        :cols => 60%>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location,
        :rows => 3,
        :cols => 60%>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,
        :rows => 3,
        :cols => 60%>
  </div>
  <div class="field">
    <%= f.label :time_start %><br />
    <%= f.datetime_select :time_start,
        :rows => 3,
        :cols => 60%>
  </div>
  <div class="field">
    <%= f.label :time_expire %><br />
    <%= f.datetime_select :time_expire,
        :rows => 3,
        :cols => 60%>
  </div>
  <!--<div class="field">
    <%# f.label :event_id %><br />
    <%# f.text_field :event_id,
        :rows => 3,
        :cols => 60%>
  </div>  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Description</th>
    <th>Time start</th>
    <th>Time expire</th>
   <!-- <th>Event</th>-->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.location %></td>
    <td><%= event.description %></td>
    <td><%= event.time_start %></td>
    <td><%= event.time_expire %></td>
    <!--<td><%= event.event_id %></td>-->
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Do you need to delete this item?', :method => :delete %></td>

    <td><a href="<%= event_path(event) %>.xml">xml file</a></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Time start:</b>
  <%= @event.time_start %>
</p>

<p>
  <b>Time expire:</b>
  <%= @event.time_expire %>
</p>

<!--<p>
  <b>Event:</b>
  <!--%= @event.event_id %>
</p> -->


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>