config/routes.rb
CTGService::Application.routes.draw do

  get "access_denied/index"

  get 'admin' => 'admin#index'

 controller :sessions do
    get 'login' => :new
    post 'login' => :login
    delete 'logout' => :logout
    get 'sign up' => :new
  end

  resources :users

  resources :event_types

  resources :upcomingevents

  root :to => "admin#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  before_filter :authenticate, :only
  # GET /event_types
  # GET /event_types.xml
  def index
    @event_types = EventType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @event_types }
    end
  end

  # GET /event_types/1
  # GET /event_types/1.xml
  def show
    @event_type = EventType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event_type }
    end
  end

  # GET /event_types/new
  # GET /event_types/new.xml
  def new
    @event_type = EventType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event_type }
    end
  end

  # GET /event_types/1/edit
  def edit
    @event_type = EventType.find(params[:id])
  end

  # POST /event_types
  # POST /event_types.xml
  def create
    @event_type = EventType.new(params[:event_type])

    respond_to do |format|
      if @event_type.save
        format.html { redirect_to(@event_type, :notice => 'Event type was successfully created.') }
        format.xml  { render :xml => @event_type, :status => :created, :location => @event_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /event_types/1
  # PUT /event_types/1.xml
  def update
    @event_type = EventType.find(params[:id])

    respond_to do |format|
      if @event_type.update_attributes(params[:event_type])
        format.html { redirect_to(@event_type, :notice => 'Event type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /event_types/1
  # DELETE /event_types/1.xml
  def destroy
    @event_type = EventType.find(params[:id])
    @event_type.destroy

    respond_to do |format|
      format.html { redirect_to(event_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/event_types_helper.rb
module EventTypesHelper
end

app/views/event_types/_form.html.erb
<%= form_for(@event_type) do |f| %>
  <% if @event_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_type.errors.count, "error") %> prohibited this event_type from being saved:</h2>

      <ul>
      <% @event_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_area :category ,
        :rows => 3,
        :cols => 60%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_types/edit.html.erb
<h1>Editing event_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_type %> |
<%= link_to 'Back', event_types_path %>

app/views/event_types/index.html.erb
<h1>Listing event_types</h1>

<table>
  <tr>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_types.each do |event_type| %>
  <tr>
    <td><%= event_type.category %></td>
    <td><%= link_to 'Show', event_type %></td>
    <td><%= link_to 'Edit', edit_event_type_path(event_type) %></td>
    <td><%= link_to 'Destroy', event_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event type', new_event_type_path %>

app/views/event_types/new.html.erb
<h1>New event_type</h1>

<%= render 'form' %>

<%= link_to 'Back', event_types_path %>

app/views/event_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @event_type.category %>
</p>


<%= link_to 'Edit', edit_event_type_path(@event_type) %> |
<%= link_to 'Back', event_types_path %>